version: 2
updates:
  - package-ecosystem: github-actions
    directories: ["/", "/wolf-pack"]
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directories: ["/", "/wolf-pack"]
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directories: ["/", "/docker"]
    schedule:
      interval: weekly
