server {
  listen 443 ssl;
  server_name api.example.com;
  ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ecdh_curve X25519MLKEM768:X25519;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;
  ssl_certificate /etc/ssl/api.crt;
  ssl_certificate_key /etc/ssl/api.key;
}
