"""Copies the site into a folder ready to publish, with the absolute addresses that search engines and link previews need.

    python site/publish.py https://www.example.com/pqc-suite/ dist
"""
import re
from html import escape
import shutil
import sys
from pathlib import Path
from urllib.parse import urljoin

SITE = Path(__file__).resolve().parent
PAGES = ["index.html", "wolf-pack.html"]


def publish(base, out):
    if not re.fullmatch(r"https://[^/\s]+/(\S*/)?", base) or any(c in base for c in '\"<>?#'):
        raise SystemExit("the address must start with https:// and end with /")
    out = Path(out)
    destination = out.resolve()
    if SITE.is_relative_to(destination) or destination.is_relative_to(SITE):
        raise SystemExit("the output must be outside the site source and must not contain it; choose a build folder such as dist/site")
    marker = out / ".pqcsuite-site-output"
    if out.is_symlink() or (out.exists() and (not out.is_dir() or any(p.is_symlink() for p in out.rglob("*")))):
        raise SystemExit("the output must be a real folder without symlinks; choose a fresh build folder")
    if out.exists() and any(out.iterdir()) and not marker.is_file():
        raise SystemExit("the output is not empty and was not created by this publisher; choose a fresh folder (existing files were kept)")
    shutil.copytree(SITE, out, dirs_exist_ok=True, ignore=shutil.ignore_patterns("publish.py", "og.html", "__pycache__"))
    for page in PAGES:
        url = urljoin(base, "" if page == "index.html" else page)
        p = out / page
        s = p.read_text(encoding="utf-8")
        s = s.replace("<head>\n", f'<head>\n<link rel="canonical" href="{escape(url, quote=True)}">\n<meta property="og:url" content="{escape(url, quote=True)}">\n', 1)
        s = re.sub(r'(<meta (?:property|name)="(?:og|twitter):image" content=")([^"]+)"', lambda m: f'{m.group(1)}{escape(urljoin(base, m.group(2)), quote=True)}"', s)
        p.write_text(s, encoding="utf-8")
    p = out / "404.html"
    p.write_text(p.read_text(encoding="utf-8").replace("<head>\n", f'<head>\n<base href="{escape(base, quote=True)}">\n', 1), encoding="utf-8")
    urls = "".join(f"  <url><loc>{escape(urljoin(base, '' if p == 'index.html' else p))}</loc></url>\n" for p in PAGES)
    (out / "sitemap.xml").write_text(f'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n{urls}</urlset>\n', encoding="utf-8")
    (out / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {urljoin(base, 'sitemap.xml')}\n", encoding="utf-8")
    marker.write_text("Generated by site/publish.py\n", encoding="utf-8")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    publish(sys.argv[1], sys.argv[2])
    print(f"published to {sys.argv[2]}")
