server {
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4';
    ssl_ecdh_curve X25519MLKEM768:X25519;
    ssl_certificate certs/server.crt;
    # ssl_protocols SSLv3 TLSv1;
}
